#pragma once

#include "types.h"
#include "ModbusCommon.h"
//#define MODBUS_MIN_ADDRESS 1
//#define MODBUS_MAX_ADDRESS 247

#define WIDGET_MODE_ID				(GUI_ID_USER + 0)
#define WIDGET_ADDRESS_ID			(GUI_ID_USER + 1)
#define WIDGET_BAUD_ID				(GUI_ID_USER + 2)
#define WIDGET_WAITING_TIME_ID		(GUI_ID_USER + 3)
#define WIDGET_FRAME_SLAVE_ID		(GUI_ID_USER + 4)
#define WIDGET_FRAME_MASTER_ID		(GUI_ID_USER + 5)
#define WIDGET_PERIOD_ID			(GUI_ID_USER + 6)
#define WIDGET_FRAME_MAIN_ID		(GUI_ID_USER + 7)

#define WIDGET_TEXT_MODE_ID			(GUI_ID_USER + 8)
#define WIDGET_TEXT_STATE_ID		(GUI_ID_USER + 9)
#define WIDGET_TEXT_TEMP_ID			(GUI_ID_USER + 10)
#define WIDGET_TEXT_PRESSURE_ID		(GUI_ID_USER + 11)
#define WIDGET_TEXT_RH_ID			(GUI_ID_USER + 12)
#define WIDGET_TEXT_RECV_ID			(GUI_ID_USER + 13)
#define WIDGET_TEXT_TRANSM_ID		(GUI_ID_USER + 14)
#define WIDGET_TEXT_FREE_BYTES_ID	(GUI_ID_USER + 15)

#define MESSAGE_SET_DATA					(WM_USER + 0)
#define MESSAGE_CREATE						(WM_USER + 1)
#define MESSAGE_MENU_CHANGED_NEXT			(WM_USER + 2)
#define MESSAGE_MENU_CHANGED_PREV			(WM_USER + 3)
#define MESSAGE_SETTINGS_MODE_CHANGED		(WM_USER + 4)

#define LEFT_X	10
#define TOP_Y	0

#define INC_YVALUE	24
#define FONT_HEIGHT	20
#define MAIN_FONT GUI_Font16B_1 
